In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('dataset/economic_index.csv')
df

Unnamed: 0  year  month  interest_rate  unemployment_rate  index_price
0            0  2017     12           2.75                5.3         1464
1            1  2017     11           2.50                5.3         1394
2            2  2017     10           2.50                5.3         1357
3            3  2017      9           2.50                5.3         1293
4            4  2017      8           2.50                5.4         1256
5            5  2017      7           2.50                5.6         1254
6            6  2017      6           2.50                5.5         1234
7            7  2017      5           2.25                5.5         1195
8            8  2017      4           2.25                5.5         1159
9            9  2017      3           2.25                5.6         1167
10          10  2017      2           2.00                5.7         1130
11          11  2017      1           2.00                5.9         1075
12          12  2016     12           2.00                6.0         1047
13          13  2016     11           1.75                5.9          965
14          14  2016     10           1.75                5.8          943
15          15  2016      9           1.75                6.1          958
16          16  2016      8           1.75                6.2          971
17          17  2016      7           1.75                6.1          949
18          18  2016      6           1.75                6.1          884
19          19  2016      5           1.75                6.1          866
20          20  2016      4           1.75                5.9          876
21          21  2016      3           1.75                6.2          822
22          22  2016      2           1.75                6.2          704
23          23  2016      1           1.75                6.1          719

In [5]:
df.head()

Unnamed: 0  year  month  interest_rate  unemployment_rate  index_price
0           0  2017     12           2.75                5.3         1464
1           1  2017     11           2.50                5.3         1394
2           2  2017     10           2.50                5.3         1357
3           3  2017      9           2.50                5.3         1293
4           4  2017      8           2.50                5.4         1256

In [13]:
df.drop(columns=['Unnamed: 0','year','month'],inplace=True,axis=1)

In [14]:
df

interest_rate  unemployment_rate  index_price
0            2.75                5.3         1464
1            2.50                5.3         1394
2            2.50                5.3         1357
3            2.50                5.3         1293
4            2.50                5.4         1256
5            2.50                5.6         1254
6            2.50                5.5         1234
7            2.25                5.5         1195
8            2.25                5.5         1159
9            2.25                5.6         1167
10           2.00                5.7         1130
11           2.00                5.9         1075
12           2.00                6.0         1047
13           1.75                5.9          965
14           1.75                5.8          943
15           1.75                6.1          958
16           1.75                6.2          971
17           1.75                6.1          949
18           1.75                6.1          884
19           1.75                6.1          866
20           1.75                5.9          876
21           1.75                6.2          822
22           1.75                6.2          704
23           1.75                6.1          719

In [6]:
x=df[['interest_rate','unemployment_rate']]
x

interest_rate  unemployment_rate
0            2.75                5.3
1            2.50                5.3
2            2.50                5.3
3            2.50                5.3
4            2.50                5.4
5            2.50                5.6
6            2.50                5.5
7            2.25                5.5
8            2.25                5.5
9            2.25                5.6
10           2.00                5.7
11           2.00                5.9
12           2.00                6.0
13           1.75                5.9
14           1.75                5.8
15           1.75                6.1
16           1.75                6.2
17           1.75                6.1
18           1.75                6.1
19           1.75                6.1
20           1.75                5.9
21           1.75                6.2
22           1.75                6.2
23           1.75                6.1

In [15]:
y=df[['index_price']]
y

index_price
0          1464
1          1394
2          1357
3          1293
4          1256
5          1254
6          1234
7          1195
8          1159
9          1167
10         1130
11         1075
12         1047
13          965
14          943
15          958
16          971
17          949
18          884
19          866
20          876
21          822
22          704
23          719

In [16]:
#train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [17]:
x_train

interest_rate  unemployment_rate
13           1.75                5.9
1            2.50                5.3
21           1.75                6.2
5            2.50                5.6
2            2.50                5.3
12           2.00                6.0
15           1.75                6.1
3            2.50                5.3
4            2.50                5.4
22           1.75                6.2
17           1.75                6.1
20           1.75                5.9
23           1.75                6.1
7            2.25                5.5
10           2.00                5.7
14           1.75                5.8
19           1.75                6.1
6            2.50                5.5

In [18]:
x_test

interest_rate  unemployment_rate
8            2.25                5.5
16           1.75                6.2
0            2.75                5.3
18           1.75                6.1
11           2.00                5.9
9            2.25                5.6

In [22]:
y_train

index_price
13          965
1          1394
21          822
5          1254
2          1357
12         1047
15          958
3          1293
4          1256
22          704
17          949
20          876
23          719
7          1195
10         1130
14          943
19          866
6          1234

In [23]:
y_test

index_price
8          1159
16          971
0          1464
18          884
11         1075
9          1167

# linearRegression

In [25]:
#apply linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [27]:
#prediction for test data
y_pred=lr.predict(x_test)
y_pred

array([[1204.22770398],
       [ 821.65051903],
       [1406.51300368],
       [ 857.70889608],
       [ 994.90992298],
       [1168.16932693]])

In [28]:
#performace metrics
import numpy as np
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [29]:
mse=mean_squared_error(y_test,y_pred)
print(mse)

5793.762887712565


In [30]:
mae=mean_absolute_error(y_test,y_pred)
print(mae)

59.935781523235505


In [33]:
r2=r2_score(y_test,y_pred)
print(r2)

0.8278978091457146


In [31]:
rmse=np.sqrt(mse)
print(rmse)

76.11677139574803


# RandomForestRegressor

In [34]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=100 , random_state=0)
rfr.fit(x_train , y_train)

C:\Users\bldea\AppData\Local\Temp\ipykernel_3584\972859175.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(x_train , y_train)


RandomForestRegressor(random_state=0)

In [35]:
#prediction for test data
y_pred1=rfr.predict(x_test)
y_pred1

array([1184.37666667,  774.78130952, 1341.53735714,  864.39983333,
       1022.54933333, 1185.69      ])

In [36]:
#performace metrics
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [37]:
mse_RFR=mean_squared_error(y_test,y_pred1)
print(mse_RFR)

9604.567277666161


In [38]:
mae_RFR=mean_absolute_error(y_test,y_pred1)
print(mae_RFR)

72.46647222222208


In [46]:
r2_RFR=r2_score(y_test,y_pred1)
print(r2_RFR)

0.7146988748539667


In [59]:
rmse_RFR=np.sqrt(mse_RFR)
print(rmse_RFR)

98.00289423106932


# SupportVectorRegression

In [41]:
from sklearn.svm import SVR
svr = SVR(kernel='rbf')
svr.fit(x_train,y_train)

C:\Users\bldea\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [42]:
y_pred2 = svr.predict(x_test)
y_pred2

array([1007.12223277, 1005.52913262, 1007.9992402 , 1005.64267741,
       1006.2427192 , 1006.99699048])

In [43]:
#performace metrics
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [44]:
mse_SVR=mean_squared_error(y_test,y_pred2)
print(mse_SVR)

46220.21296785935


In [45]:
mae_SVR=mean_absolute_error(y_test,y_pred2)
print(mae_SVR)

165.46843789896602


In [50]:
r2_SVR=r2_score(y_test,y_pred2)
print(r2_SVR)

-0.37295917483789176


In [51]:
rmse_SVR=np.sqrt(mse_SVR)
print(rmse_SVR)

214.98886707887772


# LassoRegression

In [52]:
from sklearn.linear_model import Lasso
la = Lasso(alpha=3.0)
la.fit(x_train , y_train)

Lasso(alpha=3.0)

In [53]:
y_pred3 = la.predict(x_test)
y_pred3

array([1196.63363306,  833.25124189, 1391.37273967,  866.9798988 ,
        998.07810902, 1162.90497615])

In [54]:
#performace metrics
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [55]:
mse_LA=mean_squared_error(y_test,y_pred3)
print(mse_LA)

5314.86000319994


In [56]:
mae_LA=mean_absolute_error(y_test,y_pred3)
print(mae_LA)

57.67444458909271


In [57]:
r2_LA=r2_score(y_test,y_pred3)
print(r2_LA)

0.8421234923896487


In [58]:
rmse_LA=np.sqrt(mse_LA)
print(rmse_LA)

72.9030863763664


In [60]:
df1 = pd.DataFrame({'Regression_Name':['LinearRegression','RandomForestRegression','SupportVectorRegression','LassoRegression'] , 'r2_score':[r2,r2_RFR,r2_SVR,r2_LA] , 'mse':[mse,mse_RFR,mse_SVR,mse_LA] ,'mae':[mae,mae_RFR,mae_SVR,mae_LA],'rmse':[rmse,rmse_RFR,rmse_SVR,rmse_LA]})
df1

Regression_Name  r2_score           mse         mae        rmse
0         LinearRegression  0.827898   5793.762888   59.935782   76.116771
1   RandomForestRegression  0.714699   9604.567278   72.466472   98.002894
2  SupportVectorRegression -0.372959  46220.212968  165.468438  214.988867
3          LassoRegression  0.842123   5314.860003   57.674445   72.903086