In [1]:
import numpy as np
steps_walk=[[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]]
steps_walk_arr=np.array(steps_walk)
steps_walk_arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [2]:
import numpy as np
#creating a 2d array
Day_number=np.arange(1,11)
steps_walk=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr=np.array([Day_number,steps_walk])
arr=arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [3]:
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [4]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [97]:
sortedArr=arr[arr[:,1].argsort()]
print('sorted 2d numpy array')
print(sortedArr)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [93]:
#Array Aggregation Function
#np.sum()
import numpy as np
arr8=([[1,2],[3,4]])
arr8_arr=np.array(arr8)
print(np.sum(arr8))

10


In [9]:
arr8=([[1,2],[3,4]])
arr8_arr=np.array(arr8)
print(np.sum(arr8,axis=0))

[4 6]


In [10]:
arr8=([[1,2],[3,4]])
arr8_arr=np.array(arr8)
print(np.sum(arr8,axis=1))

[3 7]


In [11]:
#np.mean()
import numpy as np
arr8=([[1,2],[3,4]])
arr8_arr=np.array(arr8)
print(np.mean(arr8))

2.5


In [12]:
arr8=([[1,2],[3,4]])
arr8_arr=np.array(arr8)
print(np.mean(arr8,axis=0))

[2. 3.]


In [13]:
arr8=([[1,2],[3,4]])
arr8_arr=np.array(arr8)
print(np.mean(arr8,axis=1))

[1.5 3.5]


In [14]:
#np.max()and np.min()
import numpy as np
x=([[1,2],[3,4]])
x_arr=np.array(x)
print(np.max(x))

4


In [15]:
x=([[1,2],[3,4]])
x_arr=np.array(x)
print(np.max(x,axis=0))

[3 4]


In [16]:
x=([[1,2],[3,4]])
x_arr=np.array(x)
print(np.max(x,axis=1))

[2 4]


In [17]:
x=([[1,2],[3,4]])
x_arr=np.array(x)
print(np.min(x))

1


In [19]:
x=([[1,2],[3,4]])
x_arr=np.array(x)
print(np.min(x,axis=0))

[1 2]


In [20]:
x=([[1,2],[3,4]])
x_arr=np.array(x)
print(np.min(x,axis=1))

[1 3]


In [21]:
#np.median()
import numpy as np
y=([[1,2],[3,4]])
y_arr=np.array(y)
print(np.median(y))

2.5


In [22]:
y=([[1,2],[3,4]])
y_arr=np.array(y)
print(np.median(y,axis=0))

[2. 3.]


In [23]:
y=([[1,2],[3,4]])
y_arr=np.array(y)
print(np.median(y,axis=1))

[1.5 3.5]


In [24]:
#np.prod()
import numpy as np
z=([[1,2],[3,4]])
z_arr=np.array(z)
print(np.prod(z))

24


In [25]:
z=([[1,2],[3,4]])
z_arr=np.array(z)
print(np.prod(z,axis=0))

[3 8]


In [26]:
z=([[1,2],[3,4]])
z_arr=np.array(z)
print(np.prod(z,axis=1))

[ 2 12]


In [28]:
#np.std()
import numpy as np
array=([[1,2],[3,4]])
array_arr=np.array(array)
print(np.std(array))

1.118033988749895


In [29]:
array=([[1,2],[3,4]])
array_arr=np.array(array)
print(np.std(array,axis=0))

[1. 1.]


In [30]:
array=([[1,2],[3,4]])
array_arr=np.array(array)
print(np.std(array,axis=1))

[0.5 0.5]


In [31]:
#np.var()
import numpy as np
array=([[1,2],[3,4]])
array_arr=np.array(array)
print(np.var(array))

1.25


In [32]:
array=([[1,2],[3,4]])
array_arr=np.array(array)
print(np.var(array,axis=0))

[1. 1.]


In [33]:
array=([[1,2],[3,4]])
array_arr=np.array(array)
print(np.var(array,axis=1))

[0.25 0.25]


In [35]:
#Vectorized Operation
#Element-wise addition:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [36]:
#Element-wise subtraction:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1-arr2
print(result)

[-3 -3 -3]


In [37]:
#Element-wise multiplication:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1*arr2
print(result)

[ 4 10 18]


In [50]:
#Element-wise division:
arr1=np.array([4,6,8])
arr2=np.array([2,3,4])
result=arr1/arr2
print(result)

[2. 2. 2.]


In [57]:
#Element-wise exponentiation:
arr=np.array([2,3,4])
result=arr**2
print(result)

[ 4  9 16]


In [58]:
#Element-wise square root:
arr=np.array([4,9,16])
result=np.sqrt(arr)
print(result)

[2. 3. 4.]


In [59]:
#Element-wise comparison:
arr1=np.array([1,2,3])
arr2=np.array([2,2,2])
result=arr1==arr2
print(result)

[False  True False]


In [61]:
#statistical function:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
result_mean=np.mean(arr)
result_std=np.std(arr,axis=1)
result_sum=np.sum(arr,axis=0)
print(result_mean)
print(result_std)
print(result_sum)

3.5
[0.81649658 0.81649658]
[5 7 9]


In [62]:
#Element-wise rounding:
import numpy as np
arr=np.array([2.3,4.7,6.1])
result=np.round(arr)
print(result)

[2. 5. 6.]


In [63]:
#Element-wise exponeniation with a scalar:
arr=np.array([2,3,4])
result=np.power(arr,2)
print(result)

[ 4  9 16]


In [64]:
#Element-wise comparison and conditional assignment:
arr=np.array([1,5,10])
result=np.where(arr<5,arr,0)
print(result)

[1 0 0]


In [66]:
#Element-wise cumulative sum:
arr=np.array([1,2,3,4,5])
result=np.cumsum(arr)
print(result)

[ 1  3  6 10 15]


In [67]:
#Element-wise sorting:
arr=np.array([3,1,4,2,5])
result=np.sort(arr)
print(result)

[1 2 3 4 5]


In [68]:
#Vectorized operation exercise:
import numpy as np
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
quarterly_difference=s_y-s_x
print(quarterly_difference)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [69]:
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
less_than_2=s_x<2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [70]:
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
x_cumsum=np.cumsum(s_x,axis=1)
print(x_cumsum)

[[ 2  7 13 18]
 [ 4 12 18 23]]


In [90]:
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
y_cumsum=np.cumsum(s_y,axis=1)
print(y_cumsum)

[[ 6 13 18 27]
 [ 7 12 18 22]]


In [74]:
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
greater_than_8=s_y>=8
print(greater_than_8)

[[False False False  True]
 [False False False False]]


In [75]:
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
yearly_mean_x=np.mean(s_x,axis=1)
print(yearly_mean_x)

[4.5  5.75]


In [79]:
s_x=np.array([[2,5,6,5],[4,8,6,5]])
s_y=np.array([[6,7,5,9],[7,5,6,4]])
quarterly_mean_y=np.mean(s_y,axis=0)
print(quarterly_mean_y)

[6.5 6.  5.5 6.5]


In [80]:
#Use Map,Filter,Reduce and Lambda Function with Numpy
#Map:
numbers=[1,2,3,4,5]
squared_numbers=map(lambda x:x ** 2,numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [81]:
#Filter
numbers=[1,2,3,4,5]
even_numbers=filter(lambda x:x % 2==0,numbers)
print(list(even_numbers))

[2, 4]


In [89]:
#Reduce
from functools import reduce
numbers=[1,2,3,4,5]
#summing all the numbers using reduce()
sum_of_numbers = reduce(lambda x,y:x+y,numbers)
print(sum_of_numbers)

15


In [84]:
#Lambda function
numbers=[1,2,3,4,5]
square=lambda x:x ** 2
print(square(5))

25
