In [1]:
import numpy as np
import pandas as pd

In [2]:
arr=np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [3]:
add1=[0,2000]
arr1=add1+arr
arr1

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [5]:
greater=np.where(arr1[:,1]>9000)
arr1[greater]

array([[    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [7]:
sort=arr1[:,1].argsort()
arr1[sort]

array([[    5,  6598],
       [    6,  7564],
       [    1,  8012],
       [    3,  8886],
       [    7,  8971],
       [    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [ ]:
df=pd.read_csv("dataset/")